<div class="bs-example">
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">JR.OİS</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">DERS İŞLEMLERİ <b class="caret"></b></a>
               <span class="dropdown-arrow"></span>
               <ul class="dropdown-menu">
                  <?php foreach($this->menu1 as $menu): ?>
                     <li><a href="/<?php echo $menu['controller'] ?>/<?php echo $menu['action'] ?>/" ><?php echo $menu['menu_adi']?></a></li>
                  <?php endforeach ?> 
               </ul>
            </li>    
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">ÖĞRETMEN İŞLEMLERİ <b class="caret"></b></a>
               <span class="dropdown-arrow"></span>
               <ul class="dropdown-menu">
                  <?php foreach($this->menu as $menu): ?>
                     <li><a href="/<?php echo $menu['controller'] ?>/<?php echo $menu['action'] ?>/" ><?php echo $menu['menu_adi'] ?> </a></li>
                  <?php endforeach ?> 
               </ul>
            </li> 
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">ÖĞRENCİ İŞLEMLERİ <b class="caret"></b></a>
               <span class="dropdown-arrow"></span>
               <ul class="dropdown-menu">
                  <?php foreach($this->menu2 as $menu): ?>
                     <li><a href="/<?php echo $menu['controller'] ?>/<?php echo $menu['action'] ?>/" ><?php echo $menu['menu_adi'] ?> </a></li>
                  <?php endforeach ?> 
               </ul>
            </li> 
          </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>