<!--
<?php if(sizeof($this->yeni)): ?>
<?php foreach($this->yeni as $anamenu=>$menu):?>
    <div class="dropdown pull-left">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
            <?php echo $anamenu ; ?>
            <span class="caret"></span>
        </button>

        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <?php foreach($menu as $j => $menuItem): ?>
                <li role="presentation"><a role="menuitem" tabindex="<?php echo $j ?>" href="/<?php echo $menuItem['controller'].'/'.$menuItem['action'] ?>"><?php echo $menuItem['menu_adi'] ?></a></li>
            <?php endforeach ?>
        </ul>

    </div>
<?php endforeach;?>
<?php endif; ?>
-->

<nav class="navbar navbar-inverse navbar-fixed-left" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">JR.OİS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <?php if(sizeof($this->yeni)): ?>
           <?php foreach($this->yeni as $anamenu=>$menu):?>
              <div class="dropdown pull-left">
                
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                  <?php echo $anamenu ; ?>
                    <span class="caret"></span>
               </button>

               <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                   <?php foreach($menu as $j => $menuItem): ?>
                       <li role="presentation"><a role="menuitem" tabindex="<?php echo $j ?>" href="/<?php echo $menuItem['controller'].'/'.$menuItem['action'] ?>"><?php echo $menuItem['menu_adi'] ?></a></li>
                   <?php endforeach ?>
               </ul>

              </div>
           <?php endforeach;?>
        <?php endif; ?>
      </ul>
   
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>