
 <form class="form-signin" role="form" action="/login/control" method="POST">
        <h2 class="form-signin-heading">Kullanıcı Girişi</h2>
        <input type="text" class="form-control" placeholder="Username" required autofocus name="kullanici_adi">
        <input type="password" class="form-control" placeholder="Password" required name="parola">
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>





       